- name: install pbm program
  hosts: mongodb
  gather_facts: yes
  roles:
    - role: backup1_install_pbm
      when: backup_or_not|bool

- name: add role/user to all shard(config+data)
  hosts: mongodb:!tag_rs_type_arbiter:!tag_server_type_mongodb_bastion
  gather_facts: yes
  roles:
    - role: backup2_db_backup_role
      when: backup_or_not|bool

- name: shard-wide setting for backup through bastion mongos
  hosts: tag_server_type_mongodb_bastion
  gather_facts: yes
  roles:
    - role: backup3_shardwide_setting
      when: backup_or_not|bool

- name: start pbm_agent service
  hosts: mongodb:!tag_server_type_mongodb_bastion
  gather_facts: yes
  roles:
    - role: backup4_start_agent
      when: backup_or_not|bool