plugin: aws_ec2

regions:
  - us-west-1 # region where mongodb place
  
filters:
  tag:server_type:
    - mongodb
    - mongodb-bastion

hostnames:
  - tag:Name
keyed_groups:
  - key: tags
    prefix: tag
    parent_group: "mongodb"
compose:
  ansible_host: private_ip_address
